// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEZWABoesb5-UrDapyLHUWJIZXfw3YR9o',
    appId: '1:610842884566:web:b56e8cc4e70edc66bf8c77',
    messagingSenderId: '610842884566',
    projectId: 'projetoaula-d3e7b',
    authDomain: 'projetoaula-d3e7b.firebaseapp.com',
    databaseURL: 'https://projetoaula-d3e7b-default-rtdb.firebaseio.com',
    storageBucket: 'projetoaula-d3e7b.firebasestorage.app',
    measurementId: 'G-FT6WL7ET5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4_1E2W_OsKtPOt5dstwoyGflNoI4nAqY',
    appId: '1:610842884566:android:7fc9114ebd23ddf0bf8c77',
    messagingSenderId: '610842884566',
    projectId: 'projetoaula-d3e7b',
    databaseURL: 'https://projetoaula-d3e7b-default-rtdb.firebaseio.com',
    storageBucket: 'projetoaula-d3e7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv_UnQbYuQmAxLrSYRf7mfiufQarl2U-Y',
    appId: '1:610842884566:ios:06bf64bc498de2e5bf8c77',
    messagingSenderId: '610842884566',
    projectId: 'projetoaula-d3e7b',
    databaseURL: 'https://projetoaula-d3e7b-default-rtdb.firebaseio.com',
    storageBucket: 'projetoaula-d3e7b.firebasestorage.app',
    iosBundleId: 'com.example.projeto1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv_UnQbYuQmAxLrSYRf7mfiufQarl2U-Y',
    appId: '1:610842884566:ios:06bf64bc498de2e5bf8c77',
    messagingSenderId: '610842884566',
    projectId: 'projetoaula-d3e7b',
    databaseURL: 'https://projetoaula-d3e7b-default-rtdb.firebaseio.com',
    storageBucket: 'projetoaula-d3e7b.firebasestorage.app',
    iosBundleId: 'com.example.projeto1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEZWABoesb5-UrDapyLHUWJIZXfw3YR9o',
    appId: '1:610842884566:web:9d6ae53a0a61e8fbbf8c77',
    messagingSenderId: '610842884566',
    projectId: 'projetoaula-d3e7b',
    authDomain: 'projetoaula-d3e7b.firebaseapp.com',
    databaseURL: 'https://projetoaula-d3e7b-default-rtdb.firebaseio.com',
    storageBucket: 'projetoaula-d3e7b.firebasestorage.app',
    measurementId: 'G-Q0GKNHF8PP',
  );
}
